# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: FormLang Help Center:FAQs, Tutorials & Troubleshooting
email: support@formlang.com
description: >- # this means to ignore newlines until "baseurl:"
  Get help with FormLang!
  Find FAQs, tutorials, troubleshooting guides & more to create powerful forms online.

baseurl: ""
url: "https://help.formlang.com"

timezone: CET

# gloabl variables
formLangBrand: <span class="fw-bold text-primary-emphasis">FormLang</span>
designApp: <a href="https://formlang.com/design" target="_blank">design App</a>
portalApp: <a href="https://formlang.com/portal" target="_blank">portal App</a>

link4OrgAccountRegister: https://portal.formlang.com/Account/Register
link4MemberRegister: https://portal.formlang.com/Account/MemberRegister

# Build settings
markdown: kramdown

# Additional folders and collections
include: ['_pages']

# Exclude from processing.
exclude:
  - LICENSE
  - doc
  - package.json
  - package-lock.json
  - Gruntfile.js
  - node_modules
  - Gemfile
  - Gemfile.lock
  - .idea/workspace.xml
  - vendor

